### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Sadeedpv** [Sadeedpv/codeExplainer#7]
Add a CONTRIBUTING.md file explaining all the contributing guidelines.

**Comment by theDevSoham** [comment]
Hey @Sadeedpv I can work on the CONTRIBUTING.md file. Could you please assign me the issue?

**Comment by Panth1823** [comment]
Hey @Sadeedpv i can make a CONTRIBUTION.md file with all needed contribution guidelines. Can u assign this issue to me?

**Comment by Sadeedpv** [comment]
@theDevSoham I just assigned you

**Comment by Sadeedpv** [comment]
Hey @Panth1823 since someone else is working on this issue, look for other issues to contribute. You can also create issues then create PR fixing those issues or you can update/fix typos in docs which is also a very valuable contribution. You could also create a decent website for the project (So far, the project does not have a website, so that could be a good first issue). If you have experience building vscode extensions, then you can bring changes to the code and improve the extension altogether.

**Comment by Panth1823** [comment]
ok cool i will look into it

**Comment by theDevSoham** [comment]
Hey @Sadeedpv the doc is complete. Only the local set up process documentation remains. Can you please give a brief flow of how the project should be set up locally and test if everything's running perfectly? It would be a great help😃

If there's a documentation please let me know. Will follow it to set up a local dev environment on my end, document the process I followed in CONTRIBUTING.md and link the documentation to the same.

Cheers😁

**Comment by Sadeedpv** [comment]
@theDevSoham all you have to do is fork the repo and clone it to your system. then, run `npm install`. Then, go to `extension.js` file and press `F5`. This will compile and run the extension in a new **Extension Development Host** window.
